#! /bin/bash

## Authors: Inés Hidalgo y Laura López
## Date: 7-12-2018

## ChIP-Seq pipeline for the analysis of two samples (chip and input)

echo "My chipseq pipeline"

## Read params
PARAMS=$1

INS_FOLDER=$(grep installation_folder $PARAMS | awk '{ print $2 }')
WORK_DIR=$(grep working_directory $PARAMS | awk '{ print $2 }')
echo $WORK_DIR
MAIN_FOLDER=$(grep main_folder $PARAMS | awk '{ print $2 }')
echo $MAIN_FOLDER
GENOME=$(grep genome_folder $PARAMS | awk '{ print $2 }')
echo $GENOME
ANNOTATION=$(grep annotation_folder $PARAMS | awk '{ print $2 }')
echo $ANNOTATION
CHIP_LOC=$(grep chip_location $PARAMS | awk '{ print $2 }')
echo $CHIP_LOC
INPUT_LOC=$(grep input_location $PARAMS | awk '{ print $2 }')
echo $INPUT_LOC

## Building working directory

cd ${WORK_DIR}
mkdir ${MAIN_FOLDER} 
cd ${MAIN_FOLDER}
mkdir genome annotation results samples log
cd samples
mkdir input chip

## Accession to genome folder

cd ../genome
cp ${GENOME} 
unzip chromosome1fa.zip 

## Building genome index

bowtie-build chromosome1.fa index

cd ../annotation
cp ${ANNOTATION}
unzip chromosome1gtf.zip

## Mapping lectures to the genome using the read_mapping.sh script

qsub -N chip -o chip ${INS_FOLDER}/read_mapping.sh ${WORK_DIR}/${MAIN_FOLDER}/samples/chip ${CHIP_LOC} chip $WORK_DIR $MAIN_FOLDER $INS_FOLDER
qsub -N input -o input ${INS_FOLDER}/read_mapping.sh ${WORK_DIR}/${MAIN_FOLDER}/samples/input ${INPUT_LOC} input $WORK_DIR $MAIN_FOLDER $INS_FOLDER
